name: Daily News Ingestion

on:
  schedule:
    - cron: "15 2 * * *" # 02:15 UTC ~ 21:15/22:15 ET depending on DST; gathers same-day items
  workflow_dispatch: {}

permissions:
  contents: read
  pull-requests: read

jobs:
  ingest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: daily-news-ingest
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci || npm install --no-audit --no-fund

      - name: Generate daily news entry
        run: npm run ingest

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(data): add daily news entry"
          title: "Automated daily news update"
          body: |
            This PR was created automatically to add the previous day's top US politics stories.

            - Please review headlines, summaries, and sources
            - Edit wording if needed for neutrality/clarity
            - Close if the day had no qualifying stories
          branch: chore/daily-news-update
          delete-branch: true
          signoff: false
          add-paths: |
            timeline-data.json
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo PR URL
        if: steps.cpr.outputs.pull-request-url
        run: |
          echo "PR: ${{ steps.cpr.outputs.pull-request-url }}"
